name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    outputs:
      deployment_successful: ${{ steps.deploy.outputs.deployment_successful }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Install Angular CLI
        run: npm install -g @angular/cli
      
      - name: Install project dependencies
        run: npm install
      
      - name: Build project
        run: npm run build
        id: build

      - name: Deploy to Firebase Hosting
        id: deploy
        if: success() # Only run deployment if previous steps were successful
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_COOKING_BLOG_DEV }}'
          channelId: live
          projectId: cooking-blog-dev
          entryPoint: src/Cooking-blog