name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/Cooking-blog/  # Add the working directory configuration here
    outputs:
      deployment_successful: ${{ steps.deploy.outputs.deployment_successful }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Install Angular CLI
        run: npm install -g @angular/cli
      
      - name: Install project dependencies
        run: npm install
      
      - name: Build project
        run: npm run build
        id: build

      - name: List contents of working directory after build
        run: ls -la

      - name: List files in dist directory
        run: dir dist

      - name: Deploy to Firebase Hosting
        id: deploy
        if: success() # Only run deployment if previous steps were successful
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_COOKING_BLOG_DEV }}'
          channelId: live
          projectId: cooking-blog-dev
          entryPoint: src/Cooking-blog